.decl Chair(x:symbol) 
.decl Course(x:symbol) 
.decl Director(x:symbol) 
.decl Employee(x:symbol) 
.decl Faculty(x:symbol) 
.decl Organization(x:symbol) 
.decl Person(x:symbol) 
.decl Professor(x:symbol) 
.decl Program(x:symbol) 
.decl Student(x:symbol) 
.decl TeachingAssistant(x:symbol) 
.decl University(x:symbol) 
.decl Work(x:symbol) 
.decl degreeFrom(x:symbol, y:symbol) 
.decl hasAlumnus(x:symbol, y:symbol) 
.decl member(x:symbol, y:symbol) 
.decl memberOf(x:symbol, y:symbol) 
.decl src_AssistantProfessor(x:symbol) 
.decl src_AssociateProfessor(x:symbol) 
.decl src_Course(x:symbol) 
.decl src_Department(x:symbol) 
.decl src_FullProfessor(x:symbol) 
.decl src_GraduateCourse(x:symbol) 
.decl src_GraduateStudent(x:symbol) 
.decl src_Lecturer(x:symbol) 
.decl src_ResearchAssistant(x:symbol) 
.decl src_ResearchGroup(x:symbol) 
.decl src_TeachingAssistant(x:symbol) 
.decl src_UndergraduateStudent(x:symbol) 
.decl src_University(x:symbol) 
.decl src_advisor(x:symbol, y:symbol) 
.decl src_doctoralDegreeFrom(x:symbol, y:symbol) 
.decl src_emailAddress(x:symbol, y:symbol) 
.decl src_headOf(x:symbol, y:symbol) 
.decl src_mastersDegreeFrom(x:symbol, y:symbol) 
.decl src_memberOf(x:symbol, y:symbol) 
.decl src_publicationAuthor(x:symbol, y:symbol) 
.decl src_subOrganizationOf(x:symbol, y:symbol) 
.decl src_takesCourse(x:symbol, y:symbol) 
.decl src_teacherOf(x:symbol, y:symbol) 
.decl src_teachingAssistantOf(x:symbol, y:symbol) 
.decl src_telephone(x:symbol, y:symbol) 
.decl src_undergraduateDegreeFrom(x:symbol, y:symbol) 
.decl src_worksFor(x:symbol, y:symbol) 
.decl subOrganizationOf(x:symbol, y:symbol) 
.decl worksFor(x:symbol, y:symbol) 
Chair(?X) :- 
   Person(?X),
   src_headOf(?X,?X1),
   src_Department(?X1).

Course(?X) :- 
   src_Course(?X).

Course(?X) :- 
   src_GraduateCourse(?X).

Course(?X1) :- 
   src_teacherOf(_,?X1).

Course(?X1) :- 
   src_teachingAssistantOf(_,?X1).

Employee(?X) :- 
   Faculty(?X).

Employee(?X) :- 
   Person(?X),
   worksFor(?X,?X1),
   Organization(?X1).

Faculty(?X) :- 
   src_Lecturer(?X).

Faculty(?X) :- 
   Professor(?X).

Faculty(?X) :- 
   src_teacherOf(?X,_).

Organization(?X) :- 
   src_Department(?X).

Organization(?X) :- 
   member(?X,_).

Organization(?X) :- 
   src_ResearchGroup(?X).

Organization(?X) :- 
   subOrganizationOf(?X,_).

Organization(?X1) :- 
   subOrganizationOf(_,?X1).

Organization(?X) :- 
   University(?X).

Person(?X) :- 
   src_advisor(?X,_).

Person(?X) :- 
   Chair(?X).

Person(?X) :- 
   degreeFrom(?X,_).

Person(?X) :- 
   src_doctoralDegreeFrom(?X,_).

Person(?X) :- 
   src_emailAddress(?X,_).

Person(?X) :- 
   Employee(?X).

Person(?X) :- 
   src_GraduateStudent(?X).

Person(?X1) :- 
   hasAlumnus(_,?X1).

Person(?X) :- 
   src_mastersDegreeFrom(?X,_).

Person(?X1) :- 
   member(_,?X1).

Person(?X1) :- 
   src_publicationAuthor(_,?X1).

Person(?X) :- 
   src_ResearchAssistant(?X).

Person(?X) :- 
   Student(?X).

Person(?X) :- 
   TeachingAssistant(?X).

Person(?X) :- 
   src_telephone(?X,_).

Person(?X) :- 
   src_undergraduateDegreeFrom(?X,_).

Professor(?X1) :- 
   src_advisor(_,?X1).

Professor(?X) :- 
   src_AssistantProfessor(?X).

Professor(?X) :- 
   src_AssociateProfessor(?X).

Professor(?X) :- 
   Chair(?X).

Professor(?X) :- 
   src_FullProfessor(?X).

Student(?X) :- 
   Person(?X),
   src_takesCourse(?X,?X1),
   Course(?X1).

Student(?X) :- 
   src_UndergraduateStudent(?X).

TeachingAssistant(?X) :- 
   src_TeachingAssistant(?X).

TeachingAssistant(?X) :- 
   Person(?X),
   src_teachingAssistantOf(?X,?X1),
   Course(?X1).

TeachingAssistant(?X) :- 
   src_teachingAssistantOf(?X,_).

University(?X) :- 
   src_University(?X).

University(?X1) :- 
   degreeFrom(_,?X1).

University(?X1) :- 
   src_doctoralDegreeFrom(_,?X1).

University(?X) :- 
   hasAlumnus(?X,_).

University(?X1) :- 
   src_mastersDegreeFrom(_,?X1).

University(?X1) :- 
   src_undergraduateDegreeFrom(_,?X1).

Work(?X) :- 
   Course(?X).

degreeFrom(?X,?Y) :- 
   src_doctoralDegreeFrom(?X,?Y).

degreeFrom(?X,?Y) :- 
   hasAlumnus(?Y,?X).

degreeFrom(?X,?Y) :- 
   src_mastersDegreeFrom(?X,?Y).

degreeFrom(?X,?Y) :- 
   src_undergraduateDegreeFrom(?X,?Y).

hasAlumnus(?X,?Y) :- 
   degreeFrom(?Y,?X).

member(?X,?Y) :- 
   memberOf(?Y,?X).

memberOf(?X,?Y) :- 
   src_memberOf(?X,?Y).

memberOf(?X,?Y) :- 
   member(?Y,?X).

memberOf(?X,?Y) :- 
   worksFor(?X,?Y).

subOrganizationOf(?X,?Y) :- 
   src_subOrganizationOf(?X,?Y).

subOrganizationOf(?X,?Z) :- 
   subOrganizationOf(?X,?Y),
   subOrganizationOf(?Y,?Z).

worksFor(?X,?Y) :- 
   src_worksFor(?X,?Y).

worksFor(?X,?Y) :- 
   src_headOf(?X,?Y).
.printsize Chair(IO="stdoutprintsize",attributeNames="x",name="Chair",operation="printsize",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.printsize Director(IO="stdoutprintsize",attributeNames="x",name="Director",operation="printsize",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.printsize Employee(IO="stdoutprintsize",attributeNames="x",name="Employee",operation="printsize",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.printsize Faculty(IO="stdoutprintsize",attributeNames="x",name="Faculty",operation="printsize",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.printsize Organization(IO="stdoutprintsize",attributeNames="x",name="Organization",operation="printsize",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.printsize Person(IO="stdoutprintsize",attributeNames="x",name="Person",operation="printsize",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.printsize Professor(IO="stdoutprintsize",attributeNames="x",name="Professor",operation="printsize",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.printsize Program(IO="stdoutprintsize",attributeNames="x",name="Program",operation="printsize",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.printsize Student(IO="stdoutprintsize",attributeNames="x",name="Student",operation="printsize",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.printsize Work(IO="stdoutprintsize",attributeNames="x",name="Work",operation="printsize",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.printsize degreeFrom(IO="stdoutprintsize",attributeNames="x	y",name="degreeFrom",operation="printsize",params="{"records": {}, "relation": {"arity": 2, "params": ["x", "y"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 2, "types": ["s:symbol", "s:symbol"]}}")

.printsize hasAlumnus(IO="stdoutprintsize",attributeNames="x	y",name="hasAlumnus",operation="printsize",params="{"records": {}, "relation": {"arity": 2, "params": ["x", "y"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 2, "types": ["s:symbol", "s:symbol"]}}")

.printsize member(IO="stdoutprintsize",attributeNames="x	y",name="member",operation="printsize",params="{"records": {}, "relation": {"arity": 2, "params": ["x", "y"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 2, "types": ["s:symbol", "s:symbol"]}}")

.input src_AssistantProfessor(IO="file",attributeNames="x",fact-dir=".",name="src_AssistantProfessor",operation="input",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.input src_AssociateProfessor(IO="file",attributeNames="x",fact-dir=".",name="src_AssociateProfessor",operation="input",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.input src_Course(IO="file",attributeNames="x",fact-dir=".",name="src_Course",operation="input",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.input src_Department(IO="file",attributeNames="x",fact-dir=".",name="src_Department",operation="input",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.input src_FullProfessor(IO="file",attributeNames="x",fact-dir=".",name="src_FullProfessor",operation="input",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.input src_GraduateCourse(IO="file",attributeNames="x",fact-dir=".",name="src_GraduateCourse",operation="input",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.input src_GraduateStudent(IO="file",attributeNames="x",fact-dir=".",name="src_GraduateStudent",operation="input",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.input src_Lecturer(IO="file",attributeNames="x",fact-dir=".",name="src_Lecturer",operation="input",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.input src_ResearchAssistant(IO="file",attributeNames="x",fact-dir=".",name="src_ResearchAssistant",operation="input",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.input src_ResearchGroup(IO="file",attributeNames="x",fact-dir=".",name="src_ResearchGroup",operation="input",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.input src_TeachingAssistant(IO="file",attributeNames="x",fact-dir=".",name="src_TeachingAssistant",operation="input",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.input src_UndergraduateStudent(IO="file",attributeNames="x",fact-dir=".",name="src_UndergraduateStudent",operation="input",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.input src_University(IO="file",attributeNames="x",fact-dir=".",name="src_University",operation="input",params="{"records": {}, "relation": {"arity": 1, "params": ["x"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 1, "types": ["s:symbol"]}}")

.input src_advisor(IO="file",attributeNames="x	y",fact-dir=".",name="src_advisor",operation="input",params="{"records": {}, "relation": {"arity": 2, "params": ["x", "y"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 2, "types": ["s:symbol", "s:symbol"]}}")

.input src_doctoralDegreeFrom(IO="file",attributeNames="x	y",fact-dir=".",name="src_doctoralDegreeFrom",operation="input",params="{"records": {}, "relation": {"arity": 2, "params": ["x", "y"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 2, "types": ["s:symbol", "s:symbol"]}}")

.input src_emailAddress(IO="file",attributeNames="x	y",fact-dir=".",name="src_emailAddress",operation="input",params="{"records": {}, "relation": {"arity": 2, "params": ["x", "y"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 2, "types": ["s:symbol", "s:symbol"]}}")

.input src_headOf(IO="file",attributeNames="x	y",fact-dir=".",name="src_headOf",operation="input",params="{"records": {}, "relation": {"arity": 2, "params": ["x", "y"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 2, "types": ["s:symbol", "s:symbol"]}}")

.input src_mastersDegreeFrom(IO="file",attributeNames="x	y",fact-dir=".",name="src_mastersDegreeFrom",operation="input",params="{"records": {}, "relation": {"arity": 2, "params": ["x", "y"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 2, "types": ["s:symbol", "s:symbol"]}}")

.input src_memberOf(IO="file",attributeNames="x	y",fact-dir=".",name="src_memberOf",operation="input",params="{"records": {}, "relation": {"arity": 2, "params": ["x", "y"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 2, "types": ["s:symbol", "s:symbol"]}}")

.input src_publicationAuthor(IO="file",attributeNames="x	y",fact-dir=".",name="src_publicationAuthor",operation="input",params="{"records": {}, "relation": {"arity": 2, "params": ["x", "y"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 2, "types": ["s:symbol", "s:symbol"]}}")

.input src_subOrganizationOf(IO="file",attributeNames="x	y",fact-dir=".",name="src_subOrganizationOf",operation="input",params="{"records": {}, "relation": {"arity": 2, "params": ["x", "y"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 2, "types": ["s:symbol", "s:symbol"]}}")

.input src_takesCourse(IO="file",attributeNames="x	y",fact-dir=".",name="src_takesCourse",operation="input",params="{"records": {}, "relation": {"arity": 2, "params": ["x", "y"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 2, "types": ["s:symbol", "s:symbol"]}}")

.input src_teacherOf(IO="file",attributeNames="x	y",fact-dir=".",name="src_teacherOf",operation="input",params="{"records": {}, "relation": {"arity": 2, "params": ["x", "y"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 2, "types": ["s:symbol", "s:symbol"]}}")

.input src_teachingAssistantOf(IO="file",attributeNames="x	y",fact-dir=".",name="src_teachingAssistantOf",operation="input",params="{"records": {}, "relation": {"arity": 2, "params": ["x", "y"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 2, "types": ["s:symbol", "s:symbol"]}}")

.input src_telephone(IO="file",attributeNames="x	y",fact-dir=".",name="src_telephone",operation="input",params="{"records": {}, "relation": {"arity": 2, "params": ["x", "y"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 2, "types": ["s:symbol", "s:symbol"]}}")

.input src_undergraduateDegreeFrom(IO="file",attributeNames="x	y",fact-dir=".",name="src_undergraduateDegreeFrom",operation="input",params="{"records": {}, "relation": {"arity": 2, "params": ["x", "y"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 2, "types": ["s:symbol", "s:symbol"]}}")

.input src_worksFor(IO="file",attributeNames="x	y",fact-dir=".",name="src_worksFor",operation="input",params="{"records": {}, "relation": {"arity": 2, "params": ["x", "y"]}}",types="{"ADTs": {}, "records": {}, "relation": {"arity": 2, "types": ["s:symbol", "s:symbol"]}}")

